'''

출처: https://school.programmers.co.kr/learn/courses/30/lessons/144853

'''


-- SELECT 
-- 	TITLE, 
--     BOARD.BOARD_ID, 
--     REPLY_ID, 
--     REPLY.WRITER_ID, 
--     REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
-- FROM USED_GOODS_REPLY AS REPLY
-- LEFT JOIN USED_GOODS_BOARD AS BOARD
-- ON REPLY.BOARD_ID = BOARD.BOARD_ID
-- BOARD.CREATED_DATE <= '2022-10-31'
-- WHERE DATE_FORMAT(BOARD.CREATED_DATE, '%Y-%m') = '2022-10'
-- ORDER BY REPLY.CREATED_DATE, TITLE

SELECT A.TITLE
    , A.BOARD_ID
    , B.REPLY_ID
    , B.WRITER_ID
    , B.CONTENTS
    , DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS A
INNER
JOIN USED_GOODS_REPLY AS B
ON A.BOARD_ID = B.BOARD_ID
WHERE SUBSTR(A.CREATED_DATE, 1, 7) = '2022-10'
ORDER
BY B.CREATED_DATE ASC, A.TITLE ASC;